version: "3"
services:
  mq:
    image: eclipse-mosquitto:1.6
    networks:
      - fleet
  fleet-api-server:
    image: fleet-api-server
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - fleet
    environment:
      - MQTT_URL=tcp://mq:1883
    ports:
      - 3000:3000
    depends_on:
      - mq
  fleet-vehicle:
    image: fleet-vehicle
    build:
      context: ./packages/vehicle
      dockerfile: ./Dockerfile_simulate
    networks:
      - fleet
    environment:
      - MQTT_URL=tcp://mq:1883
    depends_on:
      - mq
    deploy:
      mode: replicated
      replicas: 5
networks:
  fleet:
    driver: bridge