openapi: 3.0.1
info:
  title: api
  description: Package for API
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Fleet
  description: Endpoint for Fleet management
- name: Specification
  description: The swagger API specification
paths:
  /fleet:
    get:
      tags:
      - Fleet
      description: Fetch all vehicle details
      responses:
        200:
          description: Returns all vehicles
          content: {}
    post:
      tags:
      - Fleet
      description: Set data for a vehicle in fleet
      responses:
        200:
          description: Returns all examples
          content: {}
  /fleet/{uuid}:
    get:
      tags:
      - Examples
      parameters:
      - name: uuid
        in: path
        description: The uuid of the vehicle to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: Return the vehicle details with given uuid
          content: {}
        404:
          description: Vehicle not found
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
